AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  insider-case base SAM template

  Bootstraps a sample healthcheck stack (lambda + API Gateway) following the
  nested stack layout used in unified-payment-service.

Parameters:
  AppName:
    Type: String
    Default: insider-case
  EnvName:
    Type: String
    Default: dev
  Suffix:
    Type: String
    Default: ""
    Description: "Optional suffix for parallel environments (e.g. -blue)"
  ReleaseVersion:
    Type: String
    Default: "0.0.1"
  EnvTag:
    Type: String
    Default: dev
  ServiceTag:
    Type: String
    Default: insider-case

Resources:
  HealthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/health/template.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag

  MessagesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/messages/template.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag
        EnableTTL: "false"
        SharedLayerArn: !GetAtt HealthStack.Outputs.SharedLayerArn

Outputs:
  HealthApiUrl:
    Description: "Invoke URL for the healthcheck API"
    Value: !GetAtt HealthStack.Outputs.HealthApiUrl

  MessagesApiUrl:
    Description: "Invoke URL for the messages API"
    Value: !GetAtt MessagesStack.Outputs.MessagesApiUrl

  MessagesTableName:
    Description: "Name of the Messages DynamoDB table"
    Value: !GetAtt MessagesStack.Outputs.MessagesTableName

  MessagesTableArn:
    Description: "ARN of the Messages DynamoDB table"
    Value: !GetAtt MessagesStack.Outputs.MessagesTableArn

  MessagesGSIStatusCreatedAt:
    Description: "Name of the GSI for status + createdAt"
    Value: !GetAtt MessagesStack.Outputs.GSIStatusCreatedAtName

  MessagesRWPolicyArn:
    Description: "Managed policy ARN with RW/Query access to Messages table and its GSIs"
    Value: !GetAtt MessagesStack.Outputs.MessagesRWPolicyArn
