AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Healthcheck lambda resources"

Parameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  Suffix:
    Type: String
  ReleaseVersion:
    Type: String
  EnvTag:
    Type: String
  ServiceTag:
    Type: String

Globals:
  Function:
    Handler: app.lambdaHandler
    Runtime: nodejs22.x
    Timeout: 5
    MemorySize: 128
    Architectures:
      - arm64
    Tags:
      env: !Ref EnvTag
      service: !Ref ServiceTag
      Application: !Ref AppName
      ReleaseVersion: !Ref ReleaseVersion
    Environment:
      Variables:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${EnvName}-${AppName}-shared${Suffix}"
      Description: "Shared utilities (logger, helpers)"
      ContentUri: ../../src/layers/nodejs/src
      CompatibleRuntimes:
        - nodejs22.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs22.x

  HealthCheck:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${EnvName}-${AppName}-healthcheck${Suffix}"
      Description: "Returns a 200 OK for load balancers or uptime checks"
      CodeUri: ../../src/functions/healthcheck/
      Layers:
        - !Ref SharedLayer
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Minify: false
        Sourcemap: true
        Target: es2020
        Platform: node
        External:
          - aws-sdk
          - /opt/nodejs/*

Outputs:
  HealthCheckArn:
    Description: "The ARN of the healthcheck lambda"
    Value: !GetAtt HealthCheck.Arn

  SharedLayerArn:
    Description: "ARN of the shared utilities layer"
    Value: !Ref SharedLayer
