AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Health stack

  Provides a minimal example of the nested stack structure with a healthcheck
  lambda behind API Gateway.

Parameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  Suffix:
    Type: String
  ReleaseVersion:
    Type: String
  EnvTag:
    Type: String
  ServiceTag:
    Type: String

Resources:
  HealthLambdas:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambdas.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag

  HealthApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./api-gateway.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag
        HealthCheckArn: !GetAtt HealthLambdas.Outputs.HealthCheckArn

Outputs:
  HealthApiUrl:
    Description: "Invoke URL for the healthcheck endpoint"
    Value: !GetAtt HealthApiGateway.Outputs.HealthApiUrl

  SharedLayerArn:
    Description: "ARN of the shared utilities layer"
    Value: !GetAtt HealthLambdas.Outputs.SharedLayerArn
