AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Messages nested stack

Parameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  Suffix:
    Type: String
    Default: ""
  ReleaseVersion:
    Type: String
  EnvTag:
    Type: String
  ServiceTag:
    Type: String
  EnableTTL:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description: "Enable TTL on the table (attribute: expiresAt)"
  SharedLayerArn:
    Type: String
    Description: "Layer ARN providing shared utilities for lambdas"
  AuthUser:
    Type: String
    Default: "testuser"
    NoEcho: true
    Description: "Basic auth username for API lambdas (leave blank to disable)"
  AuthPass:
    Type: String
    Default: "testpass"
    NoEcho: true
    Description: "Basic auth password for API lambdas (leave blank to disable)"
  RedisUrl:
    Type: String
    Default: ""
    Description: "Redis connection URL (optional)"
  RedisTtlSeconds:
    Type: String
    Default: "0"
    Description: "Default TTL for cached entries (seconds, optional)"

Resources:
  MessagesDynamoDb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag
        EnableTTL: !Ref EnableTTL

  MessagesSqs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sqs.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag

  MessagesLambdas:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambdas.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag
        SharedLayerArn: !Ref SharedLayerArn
        AuthUser: !Ref AuthUser
        AuthPass: !Ref AuthPass
        RedisUrl: !Ref RedisUrl
        RedisTtlSeconds: !Ref RedisTtlSeconds
        # From DynamoDB nested stack
        MessagesTableName: !GetAtt MessagesDynamoDb.Outputs.MessagesTableName
        MessagesTableArn: !GetAtt MessagesDynamoDb.Outputs.MessagesTableArn
        MessagesRWPolicyArn: !GetAtt MessagesDynamoDb.Outputs.MessagesRWPolicyArn
        # From SQS nested stack
        MainQueueArn: !GetAtt MessagesSqs.Outputs.MainQueueArn
        MainQueueUrl: !GetAtt MessagesSqs.Outputs.MainQueueUrl

  MessagesApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./api-gateway.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag
        GetMessagesArn: !GetAtt MessagesLambdas.Outputs.GetMessagesArn
        PostMessagesArn: !GetAtt MessagesLambdas.Outputs.PostMessagesArn

Outputs:
  MessagesTableName:
    Description: Name of the DynamoDB Messages table
    Value: !GetAtt MessagesDynamoDb.Outputs.MessagesTableName

  MessagesTableArn:
    Description: ARN of the DynamoDB Messages table
    Value: !GetAtt MessagesDynamoDb.Outputs.MessagesTableArn

  GSIStatusCreatedAtName:
    Description: Name of the GSI used for querying by status and createdAt
    Value: !GetAtt MessagesDynamoDb.Outputs.GSIStatusCreatedAtName

  MessagesRWPolicyArn:
    Description: Managed policy ARN granting R/W/Query permissions for Messages table and GSIs
    Value: !GetAtt MessagesDynamoDb.Outputs.MessagesRWPolicyArn

  MessageSendQueueArn:
    Description: ARN of the main SQS queue (message-send-queue)
    Value: !GetAtt MessagesSqs.Outputs.MainQueueArn

  MessageSendQueueUrl:
    Description: URL of the main SQS queue (message-send-queue)
    Value: !GetAtt MessagesSqs.Outputs.MainQueueUrl

  MessageSendDlqArn:
    Description: ARN of the DLQ (message-send-dlq)
    Value: !GetAtt MessagesSqs.Outputs.DlqArn

  MessageSendWorkerArn:
    Description: ARN of the message-send-worker Lambda
    Value: !GetAtt MessagesLambdas.Outputs.MessageSendWorkerArn

  MessageDispatcherArn:
    Description: ARN of the message-dispatcher Lambda
    Value: !GetAtt MessagesLambdas.Outputs.MessageDispatcherArn

  MessagesApiUrl:
    Description: Invoke URL for messages API
    Value: !GetAtt MessagesApiGateway.Outputs.MessagesApiUrl
