AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Messages nested stack

Parameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  Suffix:
    Type: String
    Default: ""
  ReleaseVersion:
    Type: String
  EnvTag:
    Type: String
  ServiceTag:
    Type: String
  EnableTTL:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description: "Enable TTL on the table (attribute: expiresAt)"

Resources:
  MessagesDynamoDb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb.yaml
      Parameters:
        AppName: !Ref AppName
        EnvName: !Ref EnvName
        Suffix: !Ref Suffix
        ReleaseVersion: !Ref ReleaseVersion
        EnvTag: !Ref EnvTag
        ServiceTag: !Ref ServiceTag
        EnableTTL: !Ref EnableTTL

Outputs:
  MessagesTableName:
    Description: Name of the DynamoDB Messages table
    Value: !GetAtt MessagesDynamoDb.Outputs.MessagesTableName

  MessagesTableArn:
    Description: ARN of the DynamoDB Messages table
    Value: !GetAtt MessagesDynamoDb.Outputs.MessagesTableArn

  GSIStatusCreatedAtName:
    Description: Name of the GSI used for querying by status and createdAt
    Value: !GetAtt MessagesDynamoDb.Outputs.GSIStatusCreatedAtName

  MessagesRWPolicyArn:
    Description: Managed policy ARN granting R/W/Query permissions for Messages table and GSIs
    Value: !GetAtt MessagesDynamoDb.Outputs.MessagesRWPolicyArn
